/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api-schema/": {
    /**
     * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
     *
     * - YAML: application/vnd.oai.openapi
     * - JSON: application/vnd.oai.openapi+json
     */
    get: operations["api_schema_retrieve"];
  };
  "/api/aipe/chains/{chain_id}/": {
    get: operations["chains_retrieve"];
    put: operations["chains_update"];
    delete: operations["chains_destroy"];
    patch: operations["chains_partial_update"];
  };
  "/api/aipe/chains/{chain_id}/generate/": {
    post: operations["chains_generate_create"];
  };
  "/api/aipe/chains/{chain_id}/items/": {
    get: operations["chains_items_list"];
    post: operations["chains_items_create"];
  };
  "/api/aipe/contexts/": {
    get: operations["contexts_list"];
    post: operations["contexts_create"];
  };
  "/api/aipe/contexts/{context_id}/": {
    /** @description Concrete view for retrieving, updating or deleting a context instance. */
    get: operations["contexts_retrieve"];
    /** @description Concrete view for retrieving, updating or deleting a context instance. */
    put: operations["contexts_update"];
    /** @description Concrete view for retrieving, updating or deleting a context instance. */
    delete: operations["contexts_destroy"];
    /** @description Concrete view for retrieving, updating or deleting a context instance. */
    patch: operations["contexts_partial_update"];
  };
  "/api/aipe/contexts/{context_id}/spans/": {
    get: operations["contexts_spans_list"];
    post: operations["contexts_spans_create"];
  };
  "/api/aipe/contexts/{context_id}/variables/": {
    get: operations["contexts_variables_list"];
    post: operations["contexts_variables_create"];
  };
  "/api/aipe/items/{item_id}/": {
    get: operations["items_retrieve"];
    put: operations["items_update"];
    delete: operations["items_destroy"];
    patch: operations["items_partial_update"];
  };
  "/api/aipe/items/{item_id}/render_template/": {
    post: operations["items_render_template_create"];
  };
  "/api/aipe/spans/{span_id}/": {
    get: operations["spans_retrieve"];
    put: operations["spans_update"];
    delete: operations["spans_destroy"];
    patch: operations["spans_partial_update"];
  };
  "/api/aipe/spans/{span_id}/chains/": {
    get: operations["spans_chains_list"];
    post: operations["spans_chains_create"];
  };
  "/api/aipe/templates/": {
    get: operations["templates_list"];
    post: operations["templates_create"];
  };
  "/api/aipe/templates/{template_id}/": {
    get: operations["templates_retrieve"];
    put: operations["templates_update"];
    delete: operations["templates_destroy"];
    patch: operations["templates_partial_update"];
  };
  "/api/aipe/variables/{variable_id}/": {
    get: operations["variables_retrieve"];
    put: operations["variables_update"];
    delete: operations["variables_destroy"];
    patch: operations["variables_partial_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AssistantMessage: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      item_role?: components["schemas"]["ItemRoleEnum"];
      name?: string | null;
      text_content?: string | null;
      token_count?: number;
      finish_reason?: components["schemas"]["FinishReasonEnum"];
      tool_call_requests: readonly components["schemas"]["ToolCallRequest"][];
      text_content_template: components["schemas"]["MessageContentTemplate"];
      /** Format: uuid */
      text_content_template_id?: string;
    };
    AssistantMessageTyped: {
      item_type: string;
    } & components["schemas"]["AssistantMessage"];
    ChatCallChain: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      span?: string;
      title?: string;
      items: components["schemas"]["ChatItemMultiType"][];
    };
    ChatItemMultiType: components["schemas"]["UserMessageTyped"] | components["schemas"]["SystemMessageTyped"] | components["schemas"]["AssistantMessageTyped"] | components["schemas"]["ToolMessageTyped"];
    ChatSpan: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      slug: string;
      title?: string | null;
      /** Format: uuid */
      replaced_by: string | null;
      call_chains?: components["schemas"]["ChatCallChain"][];
      /** Format: uuid */
      context?: string;
    };
    ContextMemoItem: {
      /** Format: uuid */
      id: string;
      short_id?: string;
      segment: string;
      content: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    ContextVariable: {
      /** Format: uuid */
      id: string;
      name: string;
      value: unknown;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      /** Format: uuid */
      context?: string;
    };
    ConversationContext: {
      /** Format: uuid */
      id: string;
      memo_items?: components["schemas"]["ContextMemoItem"][];
      variables?: components["schemas"]["ContextVariable"][];
      spans?: components["schemas"]["ChatSpan"][];
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      title?: string | null;
      main_goal?: string | null;
    };
    /**
     * @description * `stop` - Stop
     * * `length` - Length
     * * `tool_calls` - Tool calls
     * * `content_filter` - Content filter
     * * `function_call` - Function call
     * @enum {string}
     */
    FinishReasonEnum: "stop" | "length" | "tool_calls" | "content_filter" | "function_call";
    /**
     * @description * `guardrails` - Guardrails
     * * `instructions` - Instructions
     * * `conversation` - Conversation
     * @enum {string}
     */
    ItemRoleEnum: "guardrails" | "instructions" | "conversation";
    MessageContentTemplate: {
      /** Format: uuid */
      id: string;
      name: string;
      template_text: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
    };
    PatchedAssistantMessage: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      item_role?: components["schemas"]["ItemRoleEnum"];
      name?: string | null;
      text_content?: string | null;
      token_count?: number;
      finish_reason?: components["schemas"]["FinishReasonEnum"];
      tool_call_requests?: readonly components["schemas"]["ToolCallRequest"][];
      text_content_template?: components["schemas"]["MessageContentTemplate"];
      /** Format: uuid */
      text_content_template_id?: string;
    };
    PatchedAssistantMessageTyped: {
      item_type?: string;
    } & components["schemas"]["PatchedAssistantMessage"];
    PatchedChatCallChain: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      /** Format: uuid */
      span?: string;
      title?: string;
      items?: components["schemas"]["ChatItemMultiType"][];
    };
    PatchedChatItemMultiType: components["schemas"]["PatchedUserMessageTyped"] | components["schemas"]["PatchedSystemMessageTyped"] | components["schemas"]["PatchedAssistantMessageTyped"] | components["schemas"]["PatchedToolMessageTyped"];
    PatchedChatSpan: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      slug?: string;
      title?: string | null;
      /** Format: uuid */
      replaced_by?: string | null;
      call_chains?: components["schemas"]["ChatCallChain"][];
      /** Format: uuid */
      context?: string;
    };
    PatchedContextVariable: {
      /** Format: uuid */
      id?: string;
      name?: string;
      value?: unknown;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      /** Format: uuid */
      context?: string;
    };
    PatchedConversationContext: {
      /** Format: uuid */
      id?: string;
      memo_items?: components["schemas"]["ContextMemoItem"][];
      variables?: components["schemas"]["ContextVariable"][];
      spans?: components["schemas"]["ChatSpan"][];
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      title?: string | null;
      main_goal?: string | null;
    };
    PatchedMessageContentTemplate: {
      /** Format: uuid */
      id?: string;
      name?: string;
      template_text?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    PatchedSystemMessage: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      item_role?: components["schemas"]["ItemRoleEnum"];
      name?: string | null;
      text_content?: string | null;
      token_count?: number;
      text_content_template?: components["schemas"]["MessageContentTemplate"];
      /** Format: uuid */
      text_content_template_id?: string;
    };
    PatchedSystemMessageTyped: {
      item_type?: string;
    } & components["schemas"]["PatchedSystemMessage"];
    PatchedToolMessage: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      item_role?: components["schemas"]["ItemRoleEnum"];
      call_request?: components["schemas"]["ToolCallRequest"];
      token_count?: number;
    };
    PatchedToolMessageTyped: {
      item_type?: string;
    } & components["schemas"]["PatchedToolMessage"];
    PatchedUserMessage: {
      /** Format: uuid */
      id?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
      item_role?: components["schemas"]["ItemRoleEnum"];
      name?: string | null;
      text_content?: string | null;
      token_count?: number;
      text_content_template?: components["schemas"]["MessageContentTemplate"];
      /** Format: uuid */
      text_content_template_id?: string;
    };
    PatchedUserMessageTyped: {
      item_type?: string;
    } & components["schemas"]["PatchedUserMessage"];
    /**
     * @description * `created` - Created
     * * `pending` - Pending
     * * `success` - Success
     * * `error` - Error
     * @enum {string}
     */
    StatusEnum: "created" | "pending" | "success" | "error";
    SystemMessage: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      item_role?: components["schemas"]["ItemRoleEnum"];
      name?: string | null;
      text_content?: string | null;
      token_count?: number;
      text_content_template: components["schemas"]["MessageContentTemplate"];
      /** Format: uuid */
      text_content_template_id?: string;
    };
    SystemMessageTyped: {
      item_type: string;
    } & components["schemas"]["SystemMessage"];
    ToolCallRequest: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      call_id: string;
      tool_name: string;
      tool_arguments_raw?: string | null;
      status?: components["schemas"]["StatusEnum"];
      computed_result?: string | null;
    };
    ToolMessage: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      item_role?: components["schemas"]["ItemRoleEnum"];
      call_request: components["schemas"]["ToolCallRequest"];
      token_count?: number;
    };
    ToolMessageTyped: {
      item_type: string;
    } & components["schemas"]["ToolMessage"];
    UserMessage: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      created_at: string;
      /** Format: date-time */
      updated_at: string;
      item_role?: components["schemas"]["ItemRoleEnum"];
      name?: string | null;
      text_content?: string | null;
      token_count: number;
      text_content_template: components["schemas"]["MessageContentTemplate"];
      /** Format: uuid */
      text_content_template_id?: string;
    };
    UserMessageTyped: {
      item_type: string;
    } & components["schemas"]["UserMessage"];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   */
  api_schema_retrieve: {
    parameters: {
      query?: {
        format?: "json" | "yaml";
        lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
      };
    };
    responses: {
      200: {
        content: {
          "application/vnd.oai.openapi": {
            [key: string]: unknown;
          };
          "application/yaml": {
            [key: string]: unknown;
          };
          "application/vnd.oai.openapi+json": {
            [key: string]: unknown;
          };
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  chains_retrieve: {
    parameters: {
      path: {
        chain_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatCallChain"];
        };
      };
    };
  };
  chains_update: {
    parameters: {
      path: {
        chain_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatCallChain"];
        "application/x-www-form-urlencoded": components["schemas"]["ChatCallChain"];
        "multipart/form-data": components["schemas"]["ChatCallChain"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatCallChain"];
        };
      };
    };
  };
  chains_destroy: {
    parameters: {
      path: {
        chain_id: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  chains_partial_update: {
    parameters: {
      path: {
        chain_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedChatCallChain"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedChatCallChain"];
        "multipart/form-data": components["schemas"]["PatchedChatCallChain"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatCallChain"];
        };
      };
    };
  };
  chains_generate_create: {
    parameters: {
      path: {
        chain_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ChatItemMultiType"];
        "application/x-www-form-urlencoded": components["schemas"]["ChatItemMultiType"];
        "multipart/form-data": components["schemas"]["ChatItemMultiType"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatItemMultiType"];
        };
      };
    };
  };
  chains_items_list: {
    parameters: {
      path: {
        chain_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatItemMultiType"][];
        };
      };
    };
  };
  chains_items_create: {
    parameters: {
      path: {
        chain_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ChatItemMultiType"];
        "application/x-www-form-urlencoded": components["schemas"]["ChatItemMultiType"];
        "multipart/form-data": components["schemas"]["ChatItemMultiType"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ChatItemMultiType"];
        };
      };
    };
  };
  contexts_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ConversationContext"][];
        };
      };
    };
  };
  contexts_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConversationContext"];
        "application/x-www-form-urlencoded": components["schemas"]["ConversationContext"];
        "multipart/form-data": components["schemas"]["ConversationContext"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ConversationContext"];
        };
      };
    };
  };
  /** @description Concrete view for retrieving, updating or deleting a context instance. */
  contexts_retrieve: {
    parameters: {
      path: {
        context_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ConversationContext"];
        };
      };
    };
  };
  /** @description Concrete view for retrieving, updating or deleting a context instance. */
  contexts_update: {
    parameters: {
      path: {
        context_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConversationContext"];
        "application/x-www-form-urlencoded": components["schemas"]["ConversationContext"];
        "multipart/form-data": components["schemas"]["ConversationContext"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ConversationContext"];
        };
      };
    };
  };
  /** @description Concrete view for retrieving, updating or deleting a context instance. */
  contexts_destroy: {
    parameters: {
      path: {
        context_id: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /** @description Concrete view for retrieving, updating or deleting a context instance. */
  contexts_partial_update: {
    parameters: {
      path: {
        context_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedConversationContext"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedConversationContext"];
        "multipart/form-data": components["schemas"]["PatchedConversationContext"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ConversationContext"];
        };
      };
    };
  };
  contexts_spans_list: {
    parameters: {
      path: {
        context_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatSpan"][];
        };
      };
    };
  };
  contexts_spans_create: {
    parameters: {
      path: {
        context_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ChatSpan"];
        "application/x-www-form-urlencoded": components["schemas"]["ChatSpan"];
        "multipart/form-data": components["schemas"]["ChatSpan"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ChatSpan"];
        };
      };
    };
  };
  contexts_variables_list: {
    parameters: {
      path: {
        context_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ContextVariable"][];
        };
      };
    };
  };
  contexts_variables_create: {
    parameters: {
      path: {
        context_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContextVariable"];
        "application/x-www-form-urlencoded": components["schemas"]["ContextVariable"];
        "multipart/form-data": components["schemas"]["ContextVariable"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ContextVariable"];
        };
      };
    };
  };
  items_retrieve: {
    parameters: {
      path: {
        item_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatItemMultiType"];
        };
      };
    };
  };
  items_update: {
    parameters: {
      path: {
        item_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ChatItemMultiType"];
        "application/x-www-form-urlencoded": components["schemas"]["ChatItemMultiType"];
        "multipart/form-data": components["schemas"]["ChatItemMultiType"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatItemMultiType"];
        };
      };
    };
  };
  items_destroy: {
    parameters: {
      path: {
        item_id: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  items_partial_update: {
    parameters: {
      path: {
        item_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedChatItemMultiType"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedChatItemMultiType"];
        "multipart/form-data": components["schemas"]["PatchedChatItemMultiType"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatItemMultiType"];
        };
      };
    };
  };
  items_render_template_create: {
    parameters: {
      path: {
        item_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ChatItemMultiType"];
        "application/x-www-form-urlencoded": components["schemas"]["ChatItemMultiType"];
        "multipart/form-data": components["schemas"]["ChatItemMultiType"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatItemMultiType"];
        };
      };
    };
  };
  spans_retrieve: {
    parameters: {
      path: {
        span_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatSpan"];
        };
      };
    };
  };
  spans_update: {
    parameters: {
      path: {
        span_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ChatSpan"];
        "application/x-www-form-urlencoded": components["schemas"]["ChatSpan"];
        "multipart/form-data": components["schemas"]["ChatSpan"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatSpan"];
        };
      };
    };
  };
  spans_destroy: {
    parameters: {
      path: {
        span_id: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  spans_partial_update: {
    parameters: {
      path: {
        span_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedChatSpan"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedChatSpan"];
        "multipart/form-data": components["schemas"]["PatchedChatSpan"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatSpan"];
        };
      };
    };
  };
  spans_chains_list: {
    parameters: {
      path: {
        span_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ChatCallChain"][];
        };
      };
    };
  };
  spans_chains_create: {
    parameters: {
      path: {
        span_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatCallChain"];
        "application/x-www-form-urlencoded": components["schemas"]["ChatCallChain"];
        "multipart/form-data": components["schemas"]["ChatCallChain"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["ChatCallChain"];
        };
      };
    };
  };
  templates_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MessageContentTemplate"][];
        };
      };
    };
  };
  templates_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageContentTemplate"];
        "application/x-www-form-urlencoded": components["schemas"]["MessageContentTemplate"];
        "multipart/form-data": components["schemas"]["MessageContentTemplate"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["MessageContentTemplate"];
        };
      };
    };
  };
  templates_retrieve: {
    parameters: {
      path: {
        template_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MessageContentTemplate"];
        };
      };
    };
  };
  templates_update: {
    parameters: {
      path: {
        template_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageContentTemplate"];
        "application/x-www-form-urlencoded": components["schemas"]["MessageContentTemplate"];
        "multipart/form-data": components["schemas"]["MessageContentTemplate"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MessageContentTemplate"];
        };
      };
    };
  };
  templates_destroy: {
    parameters: {
      path: {
        template_id: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  templates_partial_update: {
    parameters: {
      path: {
        template_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedMessageContentTemplate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedMessageContentTemplate"];
        "multipart/form-data": components["schemas"]["PatchedMessageContentTemplate"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MessageContentTemplate"];
        };
      };
    };
  };
  variables_retrieve: {
    parameters: {
      path: {
        variable_id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ContextVariable"];
        };
      };
    };
  };
  variables_update: {
    parameters: {
      path: {
        variable_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ContextVariable"];
        "application/x-www-form-urlencoded": components["schemas"]["ContextVariable"];
        "multipart/form-data": components["schemas"]["ContextVariable"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ContextVariable"];
        };
      };
    };
  };
  variables_destroy: {
    parameters: {
      path: {
        variable_id: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  variables_partial_update: {
    parameters: {
      path: {
        variable_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedContextVariable"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedContextVariable"];
        "multipart/form-data": components["schemas"]["PatchedContextVariable"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ContextVariable"];
        };
      };
    };
  };
}
